# Generated by Django 5.0.6 on 2024-10-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
